Repository awslabs/amazon-kinesis-video-streams-webrtc-sdk-js, pull requests merged in 2025-04, with the labels that each got.

#451 Auto-merge dependabot & retarget to develop
  .github/dependabot.yml
  .github/workflows/ci.yml
  .github/workflows/retarget-dependabot-to-develop.yml
Labels: CI

#465 Samples: Signaling reconnect and refresh/cache turn credentials
  aws-sdk-build/rename-output-file.js
  examples/app.js
  examples/channelHelper.js
  examples/index.html
  examples/master.js
Labels: Samples, 2.3.3

#463 Samples: Add the loadedData event listener only once
  examples/viewer.js
Labels: bug, Samples, cleanup, 2.3.3

#434 Update Master and Viewer Logic for Determining whether to use STUN Server
  examples/master.js
  examples/viewer.js
Labels: 2.3.3

#462 Bump project version to 2.3.3
  package-lock.json
  package.json
Labels: 2.3.3

#468 Bump version to 2.4.0
  package-lock.json
  package.json
Labels: 2.3.3

#470 Correct comment about file size for optimized build
  aws-sdk-build/webpack.config.js
Labels: Non-functional changes, 2.4.0

#476 Samples: Add the update media storage configuration to v3
  examples/updateMediaStorageConfiguration.js
Labels: 2.4.0

#477 Cleanup listeners properly
  examples/master.js
  examples/viewer.js
Labels: Samples, 2.4.0

#484 Don't run the npm publish step on forks
  .github/workflows/master-publish-gh-pages-and-npm.yml
Labels: CI, 2.4.1
